using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Web.Dtos;
using Web.Interfaces;

namespace Web.Clients
{
    /// <summary>
    /// Client to getting all characters
    /// </summary>
    public class CharacterClient : BaseClient, ICharacterClient
    {
        public CharacterClient(HttpClient client) : base(client)
        {
        }

        public async Task<List<CharacterResultResponse>> GetCharactersAsync(string url)
        {
            var result = new List<CharacterResultResponse>();

            //Calling the first page of characters
            var characterResponse = await CallGetApiAsync<CharacterResponse>(url);

            result.AddRange(characterResponse.Results);

            if (string.IsNullOrWhiteSpace(characterResponse.Info.Next)) return result;

            var pageUrl = characterResponse.Info.Next;

            //Using a Parallel.For to call all character pages
            var runner = Task.Run(() => Parallel.For(2, characterResponse.Info.Pages+1, (index) =>
            {
                var newUrl = pageUrl.Replace("page=2", $"page={index}");

                var characterPageResponse = CallGetApiAsync<CharacterResponse>(newUrl).Result;

                lock (_lock)
                {
                    result.AddRange(characterPageResponse.Results);
                }
            }));

            //Waiting until all opened threads, generated by Parallel.For, will closed
            runner.Wait();

            return result;
        }
    }
}
